CHARACTERS = [
  "Banjo & Kazooie",
  "Bayonetta",
  "Bowser",
  "Bowser Jr.",
  "Byleth",
  "Captain Falcon",
  "Chrom",
  "Cloud",
  "Corrin",
  "Daisy",
  "Dark Pit",
  "Dark Samus",
  "Diddy Kong",
  "Donkey Kong",
  "Dr. Mario",
  "Duck Hunt",
  "Falco",
  "Fox",
  "Ganondorf",
  "Greninja",
  "Hero",
  "Ice Climbers",
  "Ike",
  "Incineroar",
  "Inkling",
  "Isabelle",
  "Jigglypuff",
  "Joker",
  "Ken",
  "King Dedede",
  "King K. Rool",
  "Kirby",
  "Link",
  "Little Mac",
  "Lucario",
  "Lucas",
  "Lucina",
  "Luigi",
  "Mario",
  "Marth",
  "Mega Man",
  "Meta Knight",
  "Mewtwo",
  "Mii Brawler",
  "Mii Swordfighter",
  "Mii Gunner",
  "Min Min",
  "Mr. Game & Watch",
  "Ness",
  "Olimar",
  "Pac-Man",
  "Palutena",
  "Peach",
  "Pichu",
  "Pikachu",
  "Piranha Plant",
  "Pit",
  "Pokemon Trainer",
  "Richter",
  "Ridley",
  "R.O.B.",
  "Robin",
  "Rosalina & Luma",
  "Roy",
  "Ryu",
  "Samus",
  "Sheik",
  "Shulk",
  "Simon",
  "Snake",
  "Sonic",
  "Steve",
  "Terry",
  "Toon Link",
  "Villager",
  "Wario",
  "Wii Fit Trainer",
  "Wolf",
  "Yoshi",
  "Young Link",
  "Zelda",
  "Zero Suit Samus",
]

# left side must be lowercase 
ALIASES = Hash.new
ALIASES["rob"] = "R.O.B."
ALIASES["zss"] = "Zero Suit Samus"
ALIASES["rosa"] = "Rosalina & Luma"
ALIASES["trainer"] = "Eii Fit Trainer"
ALIASES["ddd"] = "King Dedede"
ALIASES["bowser jr"] = "Bowser Jr."
